version: "3.8"

services:
    caddy:
        build:
            context: ./docker/caddy
            args:
                UID: <LOCAL_UID>
        container_name: <GLOBAL_PREFIX>caddy
        restart: "<RESTART_POLICY>"
        ports:
            - "<FINALLY_EXPOSED_PORT>:8080"
        volumes:
            - log:/vol/log
            - rdmoapp:/vol/rdmo-app
            - ve:/vol/ve
        env_file:
            - <VARIABLES_FILE>
        depends_on:
            - rdmo

    postgres:
        build:
            context: ./docker/postgres
            args:
                UID: <LOCAL_UID>
        container_name: <GLOBAL_PREFIX>postgres
        restart: "<RESTART_POLICY>"
        volumes:
            - postgres:/var/lib/postgresql/data
        env_file:
            - <VARIABLES_FILE>

    rdmo:
        build:
            context: ./docker/rdmo
            args:
                UID: <LOCAL_UID>
        container_name: <GLOBAL_PREFIX>rdmo
        restart: "<RESTART_POLICY>"
        depends_on:
            - postgres
        volumes:
            - log:/vol/log
            - rdmoapp:/vol/rdmo-app
            - ve:/vol/ve
        env_file:
            - <VARIABLES_FILE>

volumes:
    log:
        name: <GLOBAL_PREFIX>log
        driver_opts:
            type: none
            device: <VOLDIR>/log
            o: bind
    postgres:
        name: <GLOBAL_PREFIX>postgres
        driver_opts:
            type: none
            device: <VOLDIR>/postgres
            o: bind
    rdmoapp:
        name: <GLOBAL_PREFIX>rdmoapp
        driver_opts:
            type: none
            device: <VOLDIR>/rdmo-app
            o: bind
    ve:
        name: <GLOBAL_PREFIX>ve
        driver_opts:
            type: none
            device: <VOLDIR>/ve
            o: bind
