# these are to modify the docker-compose.yaml
global_prefix = "rdc-"
finally_exposed_port = "8484"
django_secret_key = "secret_key"

# Docker restart policy (no, on-failure, always, unless-stopped)
# see https://docs.docker.com/compose/compose-file/#restart
restart_policy = "always"

# NOTE: BASE_URL does not work, will be fixed later
# by default rdmo is available under the root url
# if you want to run under a subpath set BASE_URL
# i.e. for 'http://yourrdmo.com/rdmo' set the key to '/rdmo'
# base_url=/rdmo

# the list of URLs under which this application is available
allowed_hosts = "localhost, ip6-localhost, 127.0.0.1, [::1], rdmo, rdc-rdmo"

postgres_user = "rdmo"
postgres_password = "rdmopgpass19"
postgres_db = "rdmo"
postgres_host = "postgres"
postgres_port = "5432"

# to install rdmo from github use the entry below
# if it is not set, rdmo's latest release will be installed from pip
# use with caution when switching versions on existing volume data
# migrations might be necessary which can not be undone easily
# it is highly recommended to backup the volume folder first
# also keep in mind that rdmo won't install when it is installed already
# in case of trying to update, it might be easier to do manually inside the container
# RDMO_INSTALL_URL=git+https://github.com/rdmorganiser/rdmo@1.8.2

rdmo_app = "/vol/rdmo-app"
rdmo_app_repo = "https://github.com/rdmorganiser/rdmo-app"
rdmo_catalog = "/tmp/rdmo-catalog"
rdmo_catalog_repo = "https://github.com/rdmorganiser/rdmo-catalog"

default_uri_prefix = "https://rdmo.dc/instance"

vol = "/vol"
logging_dir = "/vol/log"

# if running behind another reverse proxy, the hostname
# is required to make django set the correct url when sending an email
# caddy sets the x-forwarded-host header using this value
url_hostname = "rdmo.dc"
