---
name: build

on:
  schedule:
    - cron: "0 7 * * 1,4"
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      tags:
        description: 'manual build test'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v4
      - name: Install Task
        uses: arduino/setup-task@v2
        with:
          version: 3.x
      - name: Validate compose configuration
        run: task config
      - name: Build images
        run: task build
