---
name: build

on:
  schedule:
    - cron: "0 7 * * 1,4"
  push:
    branches:
      - master
  workflow_dispatch:
    inputs:
      tags:
        description: 'manual build test'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install gettext
        run: sudo apt update -y && sudo apt install -y gettext
      - name: Clone repo
        run: git clone https://github.com/rdmorganiser/rdmo-docker-compose.git
      - name: Try to build
        run: |
          cd rdmo-docker-compose
          make prep
          cat docker/docker-compose.yaml \
            | sed -r 's/((U|G)ID: )0/\11000/g' > dc.tmp
          cp -f dc.tmp docker/docker-compose.yaml
          cd docker && docker compose build
